/*
 * test_png_variants.c
 *
 * One PNG per pixel format a decoder has to convert -- gray at 1, 4 and 8 bits, RGB at 8
 * and 16 bits, a palette with and without tRNS, RGBA, RGB and RGBA interlaced -- and the
 * broken files, all in tests/data/png/ and generated by scripts/gen_png_fixtures.py.
 * Every valid fixture is checked pixel by pixel against the formula that generated it,
 * in colour and in grayscale, so the same expectations hold for libpng and stb_image: a
 * backend that converts a format differently fails here, not in a golden file three
 * steps later.
 *
 * The broken files fail at different stages -- the header, truncated image data, a bad
 * checksum on IHDR or on IDAT -- and each must come back as PH_ERR_CORRUPT_DATA with a diagnostic,
 * whichever decoder reads it.
 */

#include "context.h"
#include "image/image.h"
#include "libphash.h"
#include "test_macros.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FIXTURE(name) TEST_DATA_DIR "/png/" name

enum {
    SIDE = 8,
};

/* The formulas of scripts/gen_png_fixtures.py. */
static uint8_t gray8(int x, int y) { return (uint8_t)((x * 29 + y * 7) & 0xFF); }

static void rgb8(int x, int y, uint8_t out[3]) {
    out[0] = (uint8_t)((x * 32) & 0xFF);
    out[1] = (uint8_t)((y * 32) & 0xFF);
    out[2] = (uint8_t)(((x + y) * 16) & 0xFF);
}

static const uint8_t PALETTE[4][3] = {{0, 0, 0}, {255, 0, 0}, {0, 255, 0}, {0, 0, 255}};

static uint8_t to_gray(const uint8_t rgb[3]) {
    return (uint8_t)((PH_GRAY_R * rgb[0] + PH_GRAY_G * rgb[1] + PH_GRAY_B * rgb[2]) >> 7);
}

typedef void (*expect_fn)(int x, int y, uint8_t rgb[3]);

static ph_context_t *load(const char *path, int grayscale, ph_alpha_mode_t mode) {
    ph_context_t *ctx = NULL;
    ASSERT_OK(ph_create(&ctx));
    ASSERT_OK(ph_context_set_load_grayscale(ctx, grayscale));
    ASSERT_OK(ph_context_set_alpha_mode(ctx, mode));
    ph_error_t err = ph_load_from_file(ctx, path);
    if (err != PH_SUCCESS) {
        fprintf(stderr, "[FAIL] %s: %s (%s)\n", path, ph_get_error_string(err),
                ph_get_last_error_message(ctx));
        exit(1);
    }
    ASSERT_INT_EQ(SIDE, ctx->image.width);
    ASSERT_INT_EQ(SIDE, ctx->image.height);
    return ctx;
}

/* Colour load: RGB, every pixel as expected. Grayscale load: one channel, the gray of the
 * expected colour. */
static void check_fixture(const char *path, expect_fn expect, ph_alpha_mode_t mode) {
    ph_context_t *ctx = load(path, 0, mode);
    ASSERT_INT_EQ(3, ctx->image.channels);
    for (int y = 0; y < SIDE; y++) {
        for (int x = 0; x < SIDE; x++) {
            uint8_t want[3];
            expect(x, y, want);
            const uint8_t *got = &ctx->image.raw_rgb[(y * SIDE + x) * 3];
            if (memcmp(got, want, 3) != 0) {
                fprintf(stderr, "[FAIL] %s (%d,%d): got %u %u %u, expected %u %u %u\n", path, x, y,
                        got[0], got[1], got[2], want[0], want[1], want[2]);
                exit(1);
            }
        }
    }
    ph_free(ctx);

    ctx = load(path, 1, mode);
    ASSERT_INT_EQ(1, ctx->image.channels);
    for (int y = 0; y < SIDE; y++) {
        for (int x = 0; x < SIDE; x++) {
            uint8_t want[3];
            expect(x, y, want);
            uint8_t got = ctx->image.raw_rgb[y * SIDE + x];
            if (got != to_gray(want)) {
                fprintf(stderr, "[FAIL] %s grayscale (%d,%d): got %u, expected %u\n", path, x, y,
                        got, to_gray(want));
                exit(1);
            }
        }
    }
    ph_free(ctx);
}

static void gray_splat(uint8_t v, uint8_t rgb[3]) { rgb[0] = rgb[1] = rgb[2] = v; }

static void expect_gray1(int x, int y, uint8_t rgb[3]) { gray_splat((x + y) % 2 ? 255 : 0, rgb); }

static void expect_gray4(int x, int y, uint8_t rgb[3]) {
    gray_splat((uint8_t)(((x + y) % 16) * 17), rgb);
}

static void expect_gray8(int x, int y, uint8_t rgb[3]) { gray_splat(gray8(x, y), rgb); }

static void expect_rgb8(int x, int y, uint8_t rgb[3]) { rgb8(x, y, rgb); }

static void expect_palette(int x, int y, uint8_t rgb[3]) { memcpy(rgb, PALETTE[(x + y) % 4], 3); }

/* Palette entry 0 is transparent: the default background, mid-grey. */
static void expect_palette_trns(int x, int y, uint8_t rgb[3]) {
    if ((x + y) % 4 == 0) {
        gray_splat(128, rgb);
    } else {
        expect_palette(x, y, rgb);
    }
}

/* Odd columns are transparent. */
static void expect_rgba8(int x, int y, uint8_t rgb[3]) {
    if (x % 2) {
        gray_splat(128, rgb);
    } else {
        rgb8(x, y, rgb);
    }
}

static void test_valid_variants(void) {
    check_fixture(FIXTURE("gray1.png"), expect_gray1, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("gray4.png"), expect_gray4, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("gray8.png"), expect_gray8, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("rgb8.png"), expect_rgb8, PH_ALPHA_BLEND_GREY);
    /* 16 bits per sample are reduced to their high byte: the same pixels as rgb8.png. */
    check_fixture(FIXTURE("rgb16.png"), expect_rgb8, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("palette.png"), expect_palette, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("palette_trns.png"), expect_palette_trns, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("rgba8.png"), expect_rgba8, PH_ALPHA_BLEND_GREY);
    /* Adam7-interlaced: the same pixels as their plain counterparts. */
    check_fixture(FIXTURE("rgb8_interlaced.png"), expect_rgb8, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("rgba8_interlaced.png"), expect_rgba8, PH_ALPHA_BLEND_GREY);
    /* Alpha dropped: the stored colour, under transparency too. */
    check_fixture(FIXTURE("rgba8.png"), expect_rgb8, PH_ALPHA_IGNORE);
    check_fixture(FIXTURE("palette_trns.png"), expect_palette, PH_ALPHA_IGNORE);
    /* A tEXt chunk with a wrong checksum: dropped, the image decodes. */
    check_fixture(FIXTURE("ancillary_bad_crc.png"), expect_rgb8, PH_ALPHA_BLEND_GREY);
    PASS("test_valid_variants");
}

static void check_broken(const char *path, ph_error_t expected) {
    ph_context_t *ctx = NULL;
    ASSERT_OK(ph_create(&ctx));
    ph_error_t err = ph_load_from_file(ctx, path);
    if (err != expected) {
        fprintf(stderr, "[FAIL] %s: got %s, expected %s\n", path, ph_get_error_string(err),
                ph_get_error_string(expected));
        exit(1);
    }
    const char *msg = ph_get_last_error_message(ctx);
    ASSERT_PTR_NOT_NULL(msg);
    ASSERT(msg[0] != '\0');
    printf("  %s -> %s: %s\n", path, ph_get_error_string(err), msg);
    ASSERT_INT_EQ(0, ctx->image.is_loaded);
    ph_free(ctx);
}

static void test_broken_files(void) {
    check_broken(FIXTURE("broken_header.png"), PH_ERR_CORRUPT_DATA);
    check_broken(FIXTURE("broken_truncated.png"), PH_ERR_CORRUPT_DATA);
    /* A damaged checksum on the last IDAT, whose zlib stream ends exactly at the end of
     * the chunk: every PNG decoder refuses it. */
    check_broken(FIXTURE("broken_crc.png"), PH_ERR_CORRUPT_DATA);
    check_broken(FIXTURE("broken_crc_ihdr.png"), PH_ERR_CORRUPT_DATA);
#ifdef PH_USE_WEBP
    const ph_error_t webp = PH_ERR_CORRUPT_DATA;
#else
    const ph_error_t webp = PH_ERR_DECODER_UNAVAILABLE;
#endif
    check_broken(FIXTURE("broken_bitstream.webp"), webp);
    check_broken(FIXTURE("broken_truncated.webp"), webp);
    PASS("test_broken_files");
}

/* The RGB and RGBA pictures as lossless WebP decode to the PNG's pixels, in colour and in
 * grayscale: the WebP backend folds to gray with the same weights, before the alpha is
 * resolved, as the PNG one. A WebP loaded as grayscale has one channel, so the color
 * hashes refuse it as they refuse any other gray load. */
static void test_webp_matches_png(void) {
#ifdef PH_USE_WEBP
    check_fixture(FIXTURE("rgb8.webp"), expect_rgb8, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("rgba8.webp"), expect_rgba8, PH_ALPHA_BLEND_GREY);
    check_fixture(FIXTURE("rgba8.webp"), expect_rgb8, PH_ALPHA_IGNORE);

    const char *const files[] = {FIXTURE("rgb8.webp"), FIXTURE("rgba8.webp"),
                                 TEST_DATA_DIR "/photo.webp"};
    for (size_t i = 0; i < sizeof(files) / sizeof(files[0]); i++) {
        ph_context_t *ctx = NULL;
        ASSERT_OK(ph_create(&ctx));
        ASSERT_OK(ph_context_set_load_grayscale(ctx, 1));
        ASSERT_OK(ph_load_from_file(ctx, files[i]));
        ASSERT_INT_EQ(1, ctx->image.channels);
        ph_digest_t d;
        ASSERT_INT_EQ(PH_ERR_REQUIRES_COLOR, ph_compute_color_hash(ctx, &d));
        ASSERT_INT_EQ(PH_ERR_REQUIRES_COLOR, ph_compute_color_moments_hash(ctx, &d));
        ph_free(ctx);
    }
    PASS("test_webp_matches_png");
#else
    printf("test_webp_matches_png: SKIPPED (no WebP decoder in this build)\n");
#endif
}

int main(void) {
    test_valid_variants();
    test_webp_matches_png();
    test_broken_files();
    printf("test_png_variants: PASSED\n");
    return 0;
}
