/*
 * test_jpeg_variants.c
 *
 * The pixels libjpeg-turbo hands back, pinned. tests/data/jpeg/ holds one 61x45 image
 * encoded in every coding mode the decoder handles -- 4:4:4, 4:2:2, 4:4:0, 4:2:0, 4:1:1,
 * grayscale, progressive, restart markers, arithmetic coding -- generated by
 * scripts/gen_jpeg_fixtures.py. For each file, loaded in colour and in grayscale at every
 * decode_scale, the decoded size and an FNV-1a checksum of the pixels must match the table.
 *
 * The golden hashes cannot do this job: they look at a 32x32 reduction, which absorbs a
 * difference of a few levels in the decoded pixels. Anything that changes how JPEG is
 * decoded -- the IDCT, the upsampling, the colour conversion, the scaled IDCT, the
 * libjpeg-turbo version -- changes these checksums, and the failure prints the whole new
 * table.
 *
 * The table belongs to the native decoder. A build without it (stb_image decodes JPEG
 * there, with a different IDCT and no arithmetic decoding) skips the test.
 */

#include "context.h"
#include "libphash.h"
#include "test_macros.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define FIXTURE_DIR TEST_DATA_DIR "/jpeg/"

typedef struct {
    const char *file;
    int grayscale;
    ph_decode_scale_t scale;
    int width;
    int height;
    uint64_t fnv;
} jpeg_expectation_t;

static const char *const FILES[] = {
    "s444.jpg", "s422.jpg",        "s440.jpg",    "s420.jpg",       "s411.jpg",
    "gray.jpg", "progressive.jpg", "restart.jpg", "arithmetic.jpg",
};

static const ph_decode_scale_t SCALES[] = {PH_DECODE_SCALE_FULL, PH_DECODE_SCALE_HALF,
                                           PH_DECODE_SCALE_QUARTER, PH_DECODE_SCALE_EIGHTH};

static const char *const SCALE_NAMES[] = {"PH_DECODE_SCALE_FULL", "PH_DECODE_SCALE_HALF",
                                          "PH_DECODE_SCALE_QUARTER", "PH_DECODE_SCALE_EIGHTH"};

/* clang-format off */
static const jpeg_expectation_t EXPECTED[] = {
    {"s444.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x760fd19f95d05644)},
    {"s444.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x6bbedf862e8b9d3f)},
    {"s444.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xf364cf3de7010443)},
    {"s444.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0x4b8645d1b03d1392)},
    {"s444.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"s444.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"s444.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"s444.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"s422.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0xc3c27322ca32111d)},
    {"s422.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x9f2197a6646df350)},
    {"s422.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x7c3b802ecc8ae526)},
    {"s422.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0x49bc93b6c4dad3b1)},
    {"s422.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"s422.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"s422.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"s422.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"s440.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0xe5543e792e760d64)},
    {"s440.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x9c7906ae0774e0ac)},
    {"s440.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x7e0398aa3662e0f9)},
    {"s440.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xbde7d5ff0bd47ac2)},
    {"s440.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"s440.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"s440.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"s440.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"s420.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x9d1a73c7e99badad)},
    {"s420.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x3f6731da93229993)},
    {"s420.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x53c59fce7f3dfd71)},
    {"s420.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xad9b9b1ebba82b01)},
    {"s420.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"s420.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"s420.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"s420.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"s411.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x94ccb0e77320582e)},
    {"s411.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xd197a1c81ede8f24)},
    {"s411.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x4a0e6fd3b4d2c2fd)},
    {"s411.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xa81e546cefecb8b1)},
    {"s411.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"s411.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"s411.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"s411.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"gray.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x01a0d766916cc8cb)},
    {"gray.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xa649ae627e90b0bd)},
    {"gray.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x267f9f769c57d197)},
    {"gray.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xad0f5ee1f043a091)},
    {"gray.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"gray.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"gray.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"gray.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"progressive.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x9d1a73c7e99badad)},
    {"progressive.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x3f6731da93229993)},
    {"progressive.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x53c59fce7f3dfd71)},
    {"progressive.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xad9b9b1ebba82b01)},
    {"progressive.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"progressive.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"progressive.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"progressive.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"restart.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x9d1a73c7e99badad)},
    {"restart.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x3f6731da93229993)},
    {"restart.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x53c59fce7f3dfd71)},
    {"restart.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xad9b9b1ebba82b01)},
    {"restart.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"restart.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"restart.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"restart.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
    {"arithmetic.jpg", 0, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x9d1a73c7e99badad)},
    {"arithmetic.jpg", 0, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0x3f6731da93229993)},
    {"arithmetic.jpg", 0, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0x53c59fce7f3dfd71)},
    {"arithmetic.jpg", 0, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xad9b9b1ebba82b01)},
    {"arithmetic.jpg", 1, PH_DECODE_SCALE_FULL, 61, 45, UINT64_C(0x82ee081397a08b53)},
    {"arithmetic.jpg", 1, PH_DECODE_SCALE_HALF, 31, 23, UINT64_C(0xac5ebbd9dce93cd9)},
    {"arithmetic.jpg", 1, PH_DECODE_SCALE_QUARTER, 16, 12, UINT64_C(0xba0c39bf3eb33f53)},
    {"arithmetic.jpg", 1, PH_DECODE_SCALE_EIGHTH, 8, 6, UINT64_C(0xe420bec7d35c3969)},
};
/* clang-format on */

enum {
    NUM_FILES = sizeof FILES / sizeof FILES[0],
    NUM_SCALES = sizeof SCALES / sizeof SCALES[0],
    NUM_CASES = NUM_FILES * 2 * NUM_SCALES,
};

static uint64_t fnv1a(const uint8_t *p, size_t n) {
    uint64_t h = UINT64_C(0xCBF29CE484222325);
    for (size_t i = 0; i < n; i++) {
        h = (h ^ p[i]) * UINT64_C(0x100000001B3);
    }
    return h;
}

static jpeg_expectation_t decode(const char *file, int grayscale, int scale_index) {
    char path[512];
    snprintf(path, sizeof path, "%s%s", FIXTURE_DIR, file);
    ph_context_t *ctx = NULL;
    ASSERT_OK(ph_create(&ctx));
    ASSERT_OK(ph_context_set_load_grayscale(ctx, grayscale));
    ASSERT_OK(ph_context_set_decode_scale(ctx, SCALES[scale_index]));
    ph_error_t err = ph_load_from_file(ctx, path);
    if (err != PH_SUCCESS) {
        fprintf(stderr, "[FAIL] %s: %s (%s)\n", path, ph_get_error_string(err),
                ph_get_last_error_message(ctx));
        exit(1);
    }
    ASSERT_INT_EQ(grayscale ? 1 : 3, ctx->image.channels);
    jpeg_expectation_t got = {
        file,
        grayscale,
        SCALES[scale_index],
        ctx->image.width,
        ctx->image.height,
        fnv1a(ctx->image.raw_rgb,
              (size_t)ctx->image.width * (size_t)ctx->image.height * (size_t)ctx->image.channels)};
    ph_free(ctx);
    return got;
}

static void test_decoded_pixels_match_table(void) {
    static jpeg_expectation_t got[NUM_CASES];
    int n = 0, mismatches = 0;
    for (int f = 0; f < NUM_FILES; f++) {
        for (int g = 0; g < 2; g++) {
            for (int s = 0; s < NUM_SCALES; s++, n++) {
                got[n] = decode(FILES[f], g, s);
                const jpeg_expectation_t *want =
                    n < (int)(sizeof EXPECTED / sizeof EXPECTED[0]) ? &EXPECTED[n] : NULL;
                if (!want || want->grayscale != g || want->scale != SCALES[s] ||
                    want->width != got[n].width || want->height != got[n].height ||
                    want->fnv != got[n].fnv) {
                    fprintf(stderr, "[FAIL] %s %s %s: got %dx%d %016llx\n", FILES[f],
                            g ? "gray" : "rgb", SCALE_NAMES[s], got[n].width, got[n].height,
                            (unsigned long long)got[n].fnv);
                    mismatches++;
                }
            }
        }
    }
    if (mismatches) {
        fprintf(stderr,
                "%d of %d decodes differ from the table. If the change in decoding is "
                "intended, the new table is:\n",
                mismatches, NUM_CASES);
        for (int i = 0; i < NUM_CASES; i++) {
            fprintf(stderr, "    {\"%s\", %d, %s, %d, %d, UINT64_C(0x%016llx)},\n", got[i].file,
                    got[i].grayscale, SCALE_NAMES[i % NUM_SCALES], got[i].width, got[i].height,
                    (unsigned long long)got[i].fnv);
        }
        exit(1);
    }
    ASSERT_INT_EQ(NUM_CASES, (int)(sizeof EXPECTED / sizeof EXPECTED[0]));
    PASS("test_decoded_pixels_match_table");
}

int main(void) {
    if (!ph_can_use_jpeg()) {
        printf("[SKIP] test_jpeg_variants: no native JPEG decoder in this build\n");
        return 0;
    }
    test_decoded_pixels_match_table();
    return 0;
}
