#ifndef PH_LIBPHASH_H
#define PH_LIBPHASH_H

#include <stddef.h>
#include <stdint.h>

/* PH_VERSION_MAJOR/_MINOR/_PATCH/_STRING/_NUMBER: the version this header belongs to,
 * for compile-time checks (#if PH_VERSION_NUMBER >= ...). Generated by the build from
 * the project version and installed next to this file. */
#include "phash_version.h"

/**
 * @file libphash.h
 * @brief High-performance, thread-safe perceptual hashing library.
 *
 * Designed for easy FFI integration from any language with a C FFI: an opaque context
 * pointer, flat structs, and fixed-width enums.
 * All functions are thread-safe provided they operate on different contexts.
 *
 * ABI: the shared library's soname carries only the major version, so everything a
 * compiled consumer depends on stays fixed for the whole 2.x series -- function signatures, the
 * size and field offsets of every public struct, and the width and values of every public enum. New
 * functions, enumerators and error codes may be added in a minor release; nothing existing is moved
 * or reused.
 */

/**
 * @defgroup errors Errors
 * @brief Every failure is a @c ph_error_t; how to read one, and the details of the last
 *        failed load.
 *
 * @defgroup context Context
 * @brief The @c ph_context_t that holds one image and its configuration: create, free,
 *        and what is loaded.
 *
 * @defgroup loading Loading images
 * @brief From a file, a memory buffer or raw pixels, and the settings that shape the
 *        pixels at load time: grayscale, transparency, orientation, size limit, decode scale.
 *
 * @defgroup params Algorithm parameters
 * @brief Grayscale weights, gamma, and each algorithm's own tuning.
 *
 * @defgroup hash64 64-bit hashes
 * @brief aHash, dHash, pHash and wHash, alone or several at once with ph_compute_multi().
 *
 * @defgroup digests Digest hashes
 * @brief mHash, BMH, Radial, ColorHash and ColorMoments, returned as a @c ph_digest_t.
 *
 * @defgroup algorithms Algorithms as values
 * @brief Any algorithm through one call, selected by a @c ph_algorithm_t or its name.
 *
 * @defgroup compare Comparing hashes
 * @brief Distances and similarities, one per kind of digest.
 *
 * @defgroup text Hashes as text
 * @brief Storing and reading back hashes and digests as hex strings.
 *
 * @defgroup batch Batch hashing
 * @brief Many files or buffers in one call, on a pool of worker threads.
 *
 * @defgroup build Version and build
 * @brief The library's version, the decoders it was built with, and the ABI conventions.
 */

// --- Platform & Export Macros ---
#ifndef PH_API
#    if defined(_WIN32) || defined(__CYGWIN__)
// PHASH_STATIC_DEFINE: set by CMake for a STATIC build (and for anything
// linking that exported target) -- a static archive has no import library,
// so neither dllexport (this isn't the DLL build) nor dllimport (there's no
// DLL to import from) apply; PH_API must be a no-op. A build system other
// than this project's own CMakeLists.txt that links libphash statically on
// Windows must define PHASH_STATIC_DEFINE itself for the same reason.
#        ifdef PHASH_STATIC_DEFINE
#            define PH_API
#        elif defined(LIBPHASH_EXPORTS)
#            define PH_API __declspec(dllexport)
#        else
#            define PH_API __declspec(dllimport)
#        endif
#    else
#        if __GNUC__ >= 4
#            define PH_API __attribute__((visibility("default")))
#        else
#            define PH_API
#        endif
#    endif
#endif

// PH_NODISCARD must be the first thing in a declaration, ahead of PH_API:
// under C23 it is a standard attribute ([[nodiscard]]), and C23 only allows an
// attribute-specifier-sequence to open a declaration, before any GNU
// __attribute__ or type specifier. GCC enforces this and rejects
// `PH_API PH_NODISCARD T f()` outright; clang accepts it, so the wrong order
// goes unnoticed until a GCC consumer compiles in C23 (GCC 15's default).
#ifndef PH_NODISCARD
#    if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L
#        define PH_NODISCARD [[nodiscard]]
#    elif defined(__GNUC__) || defined(__clang__)
#        define PH_NODISCARD __attribute__((warn_unused_result))
#    elif defined(_MSC_VER) && _MSC_VER >= 1700
#        define PH_NODISCARD _Check_return_
#    else
#        define PH_NODISCARD
#    endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

// --- Constants ---

/** Maximum size in bytes for any digest supported by the library (128 bytes =
 * 1024 bits).
 *
 * The widest digest the library produces is the Marr-Hildreth hash at 576 bits (72
 * bytes); the rest is headroom for the color histogram's bin count, reserved so that the
 * size stays fixed for the whole 2.x series. @c ph_digest_t is passed and stored by
 * value, so it costs 136 bytes wherever one lives. @ingroup digests */
#define PH_DIGEST_MAX_BYTES 128

// --- Enum width ---

/** @brief The value of every public enum's *_FORCE_INT32_ enumerator.
 *
 * Every public enum ends in a *_FORCE_INT32_ enumerator. It is not a value any function
 * accepts or returns: it exists only to make the enum's range need a full 32-bit int, so
 * that the enum is 4 bytes wide under every compiler and flag. Without it, -fshort-enums
 * -- the default ABI on ARM EABI targets -- shrinks an enum to the smallest type that
 * holds its values, and a library and a consumer built with different settings disagree
 * on the width of every ph_error_t return value and of the `status` field in the batch
 * structs. Nothing diagnoses that mismatch; the caller just reads garbage. The width of
 * a public enum is part of the ABI. @ingroup build */
#define PH_ENUM_FORCE_INT32_VALUE 0x7FFFFFFF

// --- Error Codes ---

/**
 * @brief Result of every function that can fail: @c PH_SUCCESS (0) or a negative code.
 *
 * ph_get_error_string() names a code; ph_get_last_error_message() adds the details of the
 * last failed load on a context.
 *
 * ABI rule: every value here is spelled out explicitly, and new codes are only
 * ever appended at the end of the list (before PH_ERR_FORCE_INT32_, which is not a
 * code) with the next free negative value.
 * Renumbering or reusing a value silently changes the meaning of an error in
 * already-compiled consumers and in FFI bindings that hardcode the number, so
 * a value, once assigned, is never handed to a different code. @ingroup errors */
typedef enum {
    PH_SUCCESS = 0,                ///< The call did what it was asked.
    PH_ERR_ALLOCATION_FAILED = -1, ///< A malloc() somewhere on the call path returned NULL --
                                   ///< the input was fine, the process just could not get the
                                   ///< memory it needed right now. This is transient and worth
                                   ///< retrying, unlike PH_ERR_CORRUPT_DATA below, which is a
                                   ///< verdict on the input itself. Reported identically by the
                                   ///< native decoder backends (JPEG, PNG and WebP, on their
                                   ///< own malloc() failing) and by the stb_image fallback (on
                                   ///< stbi_load_from_memory() failing with its "outofmem"
                                   ///< reason).
    /* -2 is reserved and never assigned (see MIGRATION.md).
     * Decoding failures are reported as PH_ERR_CORRUPT_DATA, PH_ERR_UNSUPPORTED_FORMAT,
     * PH_ERR_IMAGE_TOO_LARGE, PH_ERR_IO or PH_ERR_DECODER_UNAVAILABLE. */
    PH_ERR_INVALID_ARGUMENT = -3, ///< A NULL pointer, or a value outside the documented range.
                                  ///< Always a mistake in the call itself -- a hash function
                                  ///< called before any image was loaded is
                                  ///< PH_ERR_EMPTY_IMAGE instead.
    /* -4 is reserved and never assigned (see MIGRATION.md). A feature missing from a
     * build is reported as PH_ERR_DECODER_UNAVAILABLE (a decoder) or degrades without
     * an error (threads: the batch runs sequentially). */
    PH_ERR_EMPTY_IMAGE = -5,     ///< A hash was requested from a context that holds no image:
                                 ///< nothing was loaded yet, or the last ph_load_from_file() /
                                 ///< ph_load_from_memory() failed (a failed ph_load_from_pixels()
                                 ///< keeps the previous image). Returned by every ph_compute_*
                                 ///< function and ph_compute_multi(), after their pointer
                                 ///< arguments have been checked.
    PH_ERR_IMAGE_TOO_LARGE = -6, ///< The image is larger than the context's max_pixels (see
                                 ///< ph_context_set_max_pixels()) or than the fixed limits no
                                 ///< setting lifts; or a buffer passed to a load is longer
                                 ///< than the library can address. Decided before the pixels
                                 ///< are allocated.
    PH_ERR_UNSUPPORTED_FORMAT = -7,  ///< The data isn't any image format libphash recognizes.
    PH_ERR_CORRUPT_DATA = -8,        ///< A recognized format's magic/header matched, but the
                                     ///< bitstream itself is malformed or truncated.
    PH_ERR_DECODER_UNAVAILABLE = -9, ///< The format was recognized, but no decoder for it was
                                     ///< compiled into this build (e.g. WebP without
                                     ///< PH_USE_WEBP).
    PH_ERR_IO = -10,                 ///< The path could not be used as an image source at all:
                                     ///< it does not exist (including a dangling symlink), could
                                     ///< not be opened (permissions), is not a regular file (a
                                     ///< directory, a device, a FIFO), or is an empty file. It is
                                     ///< decided before any decoder sees the bytes, and is
                                     ///< reported identically on POSIX and Windows.
    PH_ERR_REQUIRES_COLOR = -11,     ///< A color algorithm (ph_compute_color_hash(),
                                     ///< ph_compute_color_moments_hash()) was asked to run on an
                                     ///< image that carries fewer than 3 channels -- see
                                     ///< ph_context_set_load_grayscale().
    PH_ERR_CANCELLED = -12,          ///< A batch was stopped by its should_continue callback
                                     ///< (see ph_batch_options_t) before this item was
                                     ///< started. Returned by ph_hash_files_ex() /
                                     ///< ph_hash_buffers_ex() and stored in the `status` of
                                     ///< every item they never reached.
    PH_ERR_NO_STRUCTURE = -13,       ///< ph_radial_similarity() was given a digest with no
                                     ///< structure to compare: the all-zero digest
                                     ///< ph_compute_radial_hash() returns for an image with no
                                     ///< angular structure (flat, or radially symmetric).
    PH_ERR_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not an error code -- see "Enum width".
} ph_error_t;

/**
 * @brief Returns a human-readable string description for an error code.
 * @param err The error code.
 * @return A constant string describing the error. Never returns NULL.
 * @ingroup errors
 */
PH_API const char *ph_get_error_string(ph_error_t err);

/**
 * @brief Wavelet Hash operating modes.
 * @ingroup params
 */
typedef enum {
    PH_WHASH_FAST = 0, ///< A 16x16 reduction and one Haar level (default).
    PH_WHASH_FULL = 1, ///< ImageHash's scale: the largest power of two that fits, down to 8x8.
    PH_WHASH_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not a mode -- see "Enum width".
} ph_whash_mode_t;

/**
 * @brief JPEG decode resolution hint — see ph_context_set_decode_scale().
 * @ingroup loading
 */
typedef enum {
    PH_DECODE_SCALE_FULL = 0,    ///< Decode at the image's native resolution (default).
    PH_DECODE_SCALE_HALF = 1,    ///< Decode at 1/2 linear resolution (1/4 the pixels).
    PH_DECODE_SCALE_QUARTER = 2, ///< Decode at 1/4 linear resolution (1/16 the pixels).
    PH_DECODE_SCALE_EIGHTH = 3,  ///< Decode at 1/8 linear resolution (1/64 the pixels).
    PH_DECODE_SCALE_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not a scale -- see "Enum width".
} ph_decode_scale_t;

/**
 * @brief What becomes of an image's alpha channel before it is hashed — see
 *        ph_context_set_alpha_mode().
 * @ingroup loading
 */
typedef enum {
    PH_ALPHA_BLEND_GREY = 0,  ///< Composite onto mid-gray (128, 128, 128) (default).
    PH_ALPHA_BLEND_WHITE = 1, ///< Composite onto white.
    PH_ALPHA_BLEND_BLACK = 2, ///< Composite onto black.
    PH_ALPHA_IGNORE = 3,      ///< Drop alpha and hash the color stored under it, as ImageHash does.
    PH_ALPHA_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not a mode -- see "Enum width".
} ph_alpha_mode_t;

// --- Types ---

/**
 * @brief Opaque context structure holding image data and configuration.
 * Treat this as a void* in FFI.
 *
 * @note Thread-safety contract: one context per thread at a time. Distinct threads
 * each using their own @c ph_context_t may call into the library concurrently with no
 * further synchronization -- nothing here is process-global mutable state. A single
 * @c ph_context_t is not safe to use from two threads at once, including two threads
 * merely reading it concurrently (e.g. one loading a new image while another reads
 * ph_get_last_error_message()); that pairing is the caller's to serialize, not the
 * library's. ph_hash_files()/ph_hash_buffers() follow this same rule internally: each
 * worker thread in their pool creates and owns its own context. They take no context
 * themselves, so several threads may run batches at the same time. One image is always
 * loaded and hashed on a single thread -- parallelism is across images, through the
 * batch functions or the caller's own threads. See docs/batch.md.
 * @ingroup context
 */
typedef struct ph_context ph_context_t;

/**
 * @brief Returns a short diagnostic message about the most recent failure on this
 * context (e.g. the decoder-reported reason a load failed), or an empty string if
 * nothing has failed yet or no extra detail was captured.
 *
 * @note Not thread-safe to read concurrently with a load call on the same context;
 * follows the same "one context per thread at a time" rule as the rest of the API.
 * The returned pointer is owned by the context and is invalidated by the next
 * load/free call on it.
 * @param ctx The context. Passing NULL returns an empty string.
 * @ingroup errors
 */
PH_API const char *ph_get_last_error_message(const ph_context_t *ctx);

/**
 * @brief What a digest's bytes mean, and therefore how two of them may be compared.
 *
 * Not every digest is a bit vector. Comparing quantized DCT coefficients by Hamming
 * distance, or a histogram by L2, returns a plausible number that means nothing. This
 * tag exists so that such a call **fails** instead: it is never used to pick a metric
 * for you, only to refuse the wrong one. It survives storage: ph_digest_to_hex() writes
 * it into the text and ph_digest_from_hex() restores it, so two digests read back from
 * a database are protected exactly as two freshly computed ones are.
 *
 * @c PH_DIGEST_KIND_VECTOR16 is @c PH_DIGEST_KIND_VECTOR with two bytes per feature and a
 * sign, which ColorMoments needs because the third moment is a direction, not a size. The
 * two are separate tags rather than one because they are not the same bytes: comparing a
 * 16-bit vector as if it were a byte vector reads each feature's high and low halves as
 * two independent features, and returns a plausible number that means nothing.
 *
 * @c PH_DIGEST_KIND_UNSPECIFIED is what a hand-filled struct contains, since it is zero.
 * Every comparison function accepts it — an FFI binding that fills in `data` and `size`
 * and nothing else is accepted by every comparison, and gets no protection.
 * @ingroup digests
 */
typedef enum {
    PH_DIGEST_KIND_UNSPECIFIED = 0,  ///< Not stated. Accepted by every comparison.
    PH_DIGEST_KIND_BITS = 1,         ///< A bit vector. Hamming distance, similarity. BMH, mHash.
    PH_DIGEST_KIND_COEFFICIENTS = 2, ///< Quantized transform coefficients. Radial.
    PH_DIGEST_KIND_VECTOR = 3,       ///< Real-valued features, one unsigned byte each. No
                                     ///< algorithm here produces it: it tags a feature
                                     ///< vector the caller builds, compared with
                                     ///< ph_l2_distance().
    PH_DIGEST_KIND_HISTOGRAM = 4,    ///< Bin counts. Histogram intersection. ColorHash.
    PH_DIGEST_KIND_VECTOR16 = 5,     ///< Real-valued features, signed 16-bit. ColorMoments.
    PH_DIGEST_KIND_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not a kind -- see "Enum width".
} ph_digest_kind_t;

/**
 * @brief Units of a @c PH_DIGEST_KIND_VECTOR16 feature: 1/128 of a channel level.
 *
 * A @c PH_DIGEST_KIND_VECTOR16 digest holds signed 16-bit big-endian fixed-point numbers,
 * two bytes per feature, most significant byte first. Divide by this to get the value
 * back. A caller that only compares digests never needs it — ph_l2_distance() decodes
 * them — but a caller that wants the moments themselves does.
 * @ingroup digests
 */
#define PH_VECTOR16_SCALE 128

/**
 * @brief A flat structure representing a hash digest.
 *
 * @note This structure is FFI-safe and can be allocated on the stack.
 * It does not own any heap memory.
 *
 * @note The struct is 136 bytes: 128 data bytes, `size`, `kind`, and 6 bytes of padding.
 * @ingroup digests
 */
typedef struct {
    uint8_t data[PH_DIGEST_MAX_BYTES]; ///< The raw hash bytes.
    uint8_t size;                      ///< Number of valid bytes in 'data'.
    uint8_t kind;                      ///< A @c ph_digest_kind_t. 0 when not stated.
    uint8_t reserved[6];               ///< Zero. Room for future fields; makes the size a multiple
                                       ///< of 8. Not alignment: every field is a byte, so
                                       ///< _Alignof(ph_digest_t) is 1.
} ph_digest_t;

// --- Lifecycle & Configuration ---

/**
 * @brief Returns the library version string (e.g., "2.0.0").
 * @ingroup build
 */
PH_API const char *ph_version(void);

/**
 * @brief Returns the library version as a single comparable integer: the same value
 *        as the @c PH_VERSION_NUMBER macro the library was compiled with
 *        (major*1000000 + minor*1000 + patch, e.g. 2.0.0 -> 2000000).
 *        That macro comes with this header (from phash_version.h, which it includes);
 *        comparing the two tells a caller whether the header it compiled against and
 *        the library it runs with are the same version.
 *        Intended for FFI callers doing compatibility checks without string parsing.
 *
 * @note Each component has 1000 slots, so the number stays monotonic for any minor or
 *       patch up to 999.
 * @ingroup build
 */
PH_API int ph_version_number(void);

/**
 * @brief Allocates a new context with default settings (Gamma 1.0, identity).
 * @param[out] out_ctx Pointer to the created context. Untouched on error.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT for a NULL @p out_ctx, or
 *         @c PH_ERR_ALLOCATION_FAILED.
 * @ingroup context
 */
PH_NODISCARD PH_API ph_error_t ph_create(ph_context_t **out_ctx);

/**
 * @brief Frees the context and all associated image memory.
 * @param ctx The context to free. Safe to pass NULL.
 * @ingroup context
 */
PH_API void ph_free(ph_context_t *ctx);

/**
 * @name Configuration setters
 *
 * Every `ph_context_set_*` function returns @c ph_error_t, with one contract shared by
 * all of them:
 *
 *   - a valid argument (and a non-NULL @c ctx) returns @c PH_SUCCESS;
 *   - anything else returns @c PH_ERR_INVALID_ARGUMENT and leaves the configuration
 *     **completely unchanged** — values are never clamped into range, never partially
 *     applied, and never replaced by defaults.
 *
 * An invalid argument is reported rather than ignored, because a silently ignored one
 * would let a caller hash a whole batch with a configuration it never asked for. Each
 * upper bound below is a hard limit of the implementation (digest capacity, hash width, the
 * supported pixel ceiling), not a style preference.
 *
 * @note These setters are intentionally not `warn_unused_result`: they are commonly
 *       called with compile-time-constant arguments where the result carries no
 *       information. Check the return value whenever the argument comes from outside
 *       your code.
 * @{
 */

/**
 * @brief Sets the gamma value applied by ph_compute_radial_hash(), and by nothing else.
 *
 * Applied to the blurred grayscale image before the radial projections:
 * `out = (in / max)^gamma * max`, where `max` is the brightest value in it, as pHash
 * applies it. The default, 1.0, is the identity, and the step is skipped.
 *
 * @warning Despite living on the context, this setting affects **only** the Radial
 *          hash; every other algorithm ignores it. See docs/theory/radial.md.
 *
 * @param ctx The context.
 * @param gamma The gamma value (e.g., 1.0). Must be finite and in (0.001, 1000]; NaN and
 *        infinities are rejected.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or an
 *         out-of-range @p gamma.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_gamma(ph_context_t *ctx, float gamma);

/**
 * @brief Sets custom RGB-to-Grayscale weights.
 *
 * Input values are automatically normalized to sum to 128 for optimized internal
 * processing. Default is PH_GRAY_R=38, PH_GRAY_G=75, PH_GRAY_B=15 (sum 128).
 *
 * @param ctx The context.
 * @param r,g,b Relative channel weights. Each must be >= 0, their sum must be > 0 and
 *              at most INT_MAX / 255 (8421504), so that the normalization stays inside
 *              `int`.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx, a negative
 *         weight, or a sum outside the range above.
 *
 * @note A zero sum is an error, not a request for the defaults: the configuration is
 *       never replaced by something the caller did not ask for.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_gray_weights(ph_context_t *ctx, int r, int g, int b);

/**
 * @brief Reads back the grayscale weights the context actually uses.
 *
 * These are the normalized values, summing to 128, not the ones passed to
 * ph_context_set_gray_weights(): (100, 10, 18) is stored as (100, 10, 18) because it
 * already sums to 128, but (1, 1, 1) is stored as (42, 42, 44). The only configuration
 * getter, because this is the only setter that transforms its input; the others store
 * exactly what they were given.
 * @param ctx The context.
 * @param[out] r,g,b Receive the weights. None may be NULL.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for a NULL argument (nothing is
 *         written then).
 * @ingroup params
 */
PH_NODISCARD PH_API ph_error_t ph_context_get_gray_weights(const ph_context_t *ctx, int *r, int *g,
                                                           int *b);

/**
 * @brief Sets pHash parameters.
 *
 * Out-of-range values are rejected and the current configuration is left unchanged; they
 * are never clamped. If an out-of-range value reaches ph_compute_phash() by other means,
 * it returns @c PH_ERR_INVALID_ARGUMENT and leaves the output untouched. See
 * docs/theory/phash.md.
 *
 * @param ctx The context.
 * @param dct_size The side of the grid the image is reduced to and of its DCT,
 *                 @p reduction_size..32 (default 32).
 * @param reduction_size The side of the low-frequency block of coefficients the hash is
 *                       made of, 4..8 (default 8): the hash has reduction_size^2 bits, of
 *                       which the DC coefficient's is always set. Below 4 the hash is
 *                       degenerate; above 8 it would not fit 64 bits.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or an
 *         out-of-range pair.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_phash_params(ph_context_t *ctx, int dct_size, int reduction_size);

/**
 * @brief Sets Radial Hash parameters.
 *
 * The digest is 40 bytes whatever the settings, so digests computed with different ones
 * cannot be told apart by size; compare only digests computed alike. The cost of the
 * projections is projections * samples, whatever the image size, and the digest converges
 * long before the upper bounds, which keep a configuration from an untrusted source from
 * costing seconds per call. See docs/theory/radial.md.
 *
 * @param ctx The context.
 * @param projections Number of lines through the center, spread over [0, pi), 40..4096
 *        (default 180). Fewer than 40 would give fewer than the 40 DCT coefficients the
 *        digest holds.
 * @param samples Points read on each line, 2..4096 (default 128). One point has no
 *        variance, so every image would have no angular structure.
 * @param sigma Gaussian blur sigma applied before the projections, in (0, 64/3]
 *        (default 3.5, pHash's). Above 64/3 the blur's kernel would be silently
 *        narrower than requested.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or an
 *         out-of-range value; the configuration is unchanged on error.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_radial_params(ph_context_t *ctx, int projections, int samples,
                                               float sigma);

/**
 * @brief Sets the grid resolution for the Block Mean Hash (BMH).
 *
 * @param ctx The context.
 * @param block_size Resolution of the grid, 2..32 (default 16): `block_size * block_size`
 *        blocks, one bit each. 32 is the largest grid whose bits fit a @c ph_digest_t
 *        (1024 bits, PH_DIGEST_MAX_BYTES); at 1 every image would give the same bit. An
 *        out-of-range value is refused, not clamped.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or an
 *         out-of-range @p block_size.
 *
 * @note This affects BMH only; mHash has its own parameters, see
 *       ph_context_set_mhash_params(). See docs/theory/bmh.md.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_block_params(ph_context_t *ctx, int block_size);

/**
 * @brief Sets the Marr-Hildreth hash's kernel scale and normalization size.
 *
 * @p alpha and @p level set the Laplacian-of-Gaussian kernel: it reaches
 * `floor(4 * alpha^level)` samples from its center (a 17x17 kernel at the defaults), and a
 * wider kernel describes coarser detail. @p size is the side the image is normalized to;
 * the grid stays 31x31 blocks of `size / 31` pixels, so the digest is always 576 bits.
 * The defaults, 2, 1 and 512, are pHash's. Digests are comparable only when computed with
 * the same values. See docs/theory/mhash.md.
 *
 * @param ctx The context.
 * @param alpha Scale base, > 1 and finite.
 * @param level Scale exponent, >= 0 and finite. `4 * alpha^level` must be at least 1 and
 *        must keep the kernel side at 65 or below.
 * @param size Normalization side, 62..4096.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or any value out of
 *         range, with the configuration left untouched.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_mhash_params(ph_context_t *ctx, float alpha, float level,
                                              int size);

/**
 * @brief Sets the operating mode for Wavelet Hash (wHash).
 *
 * @param ctx The context.
 * @param mode PH_WHASH_FAST (0, the default): a fixed 16x16 scale and one Haar level, a
 *             cost independent of the image beyond the shared downscale. PH_WHASH_FULL (1):
 *             the largest power-of-two scale that fits the image, cascaded down to 8x8 --
 *             closer to ImageHash, and its cost grows with the image. The two hashes
 *             are not interchangeable. See docs/theory/whash.md.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or a @p mode that
 *         is not one of the declared enumerators.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_whash_mode(ph_context_t *ctx, ph_whash_mode_t mode);

/**
 * @brief Controls wHash's removal of the coarsest LL band (ImageHash's
 *        @c remove_max_haar_ll). Off by default.
 *
 * Zeroing the coarsest LL coefficient and reconstructing subtracts the image mean from
 * every sample, which shifts the working LL band and its median alike: the only bits it
 * can change are those of values that tie with the median, and it decides them by
 * rounding error. Offered for callers who mirror ImageHash's configuration, where it is
 * on. See docs/theory/whash.md.
 *
 * @param ctx The context.
 * @param enable Non-zero to zero the coarsest LL coefficient before the working
 *        decomposition, zero to leave it in place.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx.
 * @ingroup params
 */
PH_API ph_error_t ph_context_set_whash_remove_max_haar_ll(ph_context_t *ctx, int enable);

/**
 * @brief Controls whether ph_load_from_file() and ph_load_from_memory() ask the decoder
 *        for one grayscale channel instead of color. Off by default.
 *
 * A grayscale load skips the library's color-to-gray conversion, and for JPEG the
 * decoder's color conversion as well; a JPEG's grayscale is then the luma the file stores,
 * which can differ from the library's conversion by a level. WebP has no grayscale decode
 * and is loaded in color whatever the setting. The setting applies from the next load.
 *
 * @note A single-channel image has no color statistics: on one, ph_compute_color_hash()
 *       and ph_compute_color_moments_hash(), and ph_compute_digest() for either, fail with
 *       @c PH_ERR_REQUIRES_COLOR. Load in color if you need them.
 *
 * When it pays, and what it changes in a hash: docs/guide/loading.md.
 *
 * @param ctx The context.
 * @param enable 1 to enable grayscale loading, 0 to disable (load native channels).
 *               Any non-zero value enables it.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT only for a NULL @p ctx — every
 *         @c int is a valid flag value.
 * @ingroup loading
 */
PH_API ph_error_t ph_context_set_load_grayscale(ph_context_t *ctx, int enable);

/**
 * @brief Chooses what an image's alpha channel does to the hash.
 *
 * A transparent pixel looks like whatever is behind it, and the color stored under alpha 0
 * is invisible and differs from encoder to encoder. By default every image with alpha — a
 * PNG or WebP with an alpha channel or a tRNS chunk, or a 4-channel buffer given to
 * ph_load_from_pixels() — is composited onto mid-gray before anything else happens, per
 * channel `(c * a + bg * (255 - a) + 127) / 255`, so the hash follows the visible image
 * only. What ignoring alpha costs, and which background suits which algorithm, is measured
 * in docs/theory/preparation.md.
 *
 * The mode applies at load time: set it before ph_load_from_file(),
 * ph_load_from_memory() or ph_load_from_pixels(). A loaded image never has an alpha
 * channel, so ph_context_get_dimensions() reports 3 channels (1 when loaded as
 * grayscale) for an image that had one.
 *
 * @param ctx The context.
 * @param mode @c PH_ALPHA_BLEND_GREY (default), @c PH_ALPHA_BLEND_WHITE,
 *        @c PH_ALPHA_BLEND_BLACK, or @c PH_ALPHA_IGNORE to hash the stored color
 *        whatever its alpha, which is what ImageHash (and PIL's `convert("L")`) does.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or a @p mode that
 *         is not one of the enumerators above (configuration unchanged).
 * @ingroup loading
 */
PH_API ph_error_t ph_context_set_alpha_mode(ph_context_t *ctx, ph_alpha_mode_t mode);

/**
 * @brief Controls whether the EXIF orientation is applied right after decoding. On by
 * default.
 *
 * When enabled, the `Orientation` tag (values 1-8) of a JPEG's Exif segment, a WebP's
 * `EXIF` chunk or a PNG's `eXIf` chunk is applied, turning or mirroring the image before
 * any hash, so that a hash describes the picture as a viewer shows it. When disabled, the
 * pixels are hashed as stored. ph_load_from_pixels() carries no orientation. The setting
 * applies from the next load. See docs/theory/preparation.md.
 *
 * @note A missing or malformed tag reads as 1, no transform; it never fails a load.
 * @note Applying an orientation of 2-8 takes a second buffer the size of the decoded
 * image. If it cannot be allocated, the load returns @c PH_ERR_ALLOCATION_FAILED and no
 * image is loaded, rather than an image in an orientation you did not ask for.
 * @param ctx The context.
 * @param enable 1 to auto-orient using EXIF metadata (default), 0 to hash the
 * raw decoded buffer as-is. Any non-zero value enables it.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT only for a NULL @p ctx — every
 *         @c int is a valid flag value.
 * @ingroup loading
 */
PH_API ph_error_t ph_context_set_auto_orient(ph_context_t *ctx, int enable);

/**
 * @brief Sets the most pixels, width * height, an image may have. Checked against the
 *        dimensions a file declares, before any pixel buffer is allocated, so that a small
 *        file declaring an enormous image is refused cheaply.
 *
 * An image over the limit fails to load with @c PH_ERR_IMAGE_TOO_LARGE. Two fixed limits
 * apply whatever is set here: INT_MAX (2147483647) pixels, as the library indexes pixels
 * in `int`; and, for ph_load_from_file() and ph_load_from_memory() only, 1000000 pixels on
 * either side, so that an image of one enormous row cannot pass the area limit.
 * ph_load_from_pixels() is held to the pixel count only. See docs/guide/loading.md.
 *
 * @param ctx The context.
 * @param max_pixels The limit; 256 * 1024 * 1024 by default. 0 removes it, leaving the
 *        fixed limits.
 *
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT only for a NULL @p ctx. Every
 *         @c uint64_t is accepted, including values above the implementation ceiling:
 *         the ceiling is applied when an image is loaded, not when the limit is set.
 * @ingroup loading
 */
PH_API ph_error_t ph_context_set_max_pixels(ph_context_t *ctx, uint64_t max_pixels);

/**
 * @brief Requests that JPEG be decoded at a reduced resolution instead of natively,
 *        trading accuracy for decode speed. Full resolution by default.
 *
 * libjpeg-turbo decodes at 1/2, 1/4 or 1/8 of the width and height by scaling in the DCT
 * domain, rounding a side that does not divide evenly up. The decode itself gets somewhat
 * cheaper, and everything after it -- the grayscale conversion, and each hash's reduction,
 * blur or histogram -- reads four times fewer pixels at each step. Every hash then
 * describes the smaller image, so its value changes; by how much depends on the algorithm
 * and on the decoded size. Both the saving and the change are measured in
 * docs/theory/preparation.md.
 *
 * @note Only the JPEG backend honors this. A PNG, a WebP, or a JPEG in a build whose JPEG
 *       decoder is stb_image is decoded at full resolution whatever the setting, and
 *       ph_load_from_pixels() has no decoder at all. The @c max_pixels limit is judged by
 *       a JPEG's full dimensions.
 *
 * @param ctx The context.
 * @param scale The requested decode resolution. @c PH_DECODE_SCALE_FULL is the default.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for NULL @p ctx or a @p scale that
 *         is not one of the declared enumerators.
 * @ingroup loading
 */
PH_API ph_error_t ph_context_set_decode_scale(ph_context_t *ctx, ph_decode_scale_t scale);

/** @} */

/**
 * @brief Returns the dimensions of the currently loaded image.
 *
 * With no image loaded -- a fresh context, or one whose last ph_load_from_file() /
 * ph_load_from_memory() failed -- every output is set to 0. A failed
 * ph_load_from_pixels() is the exception: it keeps the previous image, and so its
 * dimensions. ph_is_loaded() tells "no image" apart from anything else.
 * @param ctx The context. With NULL, nothing is written.
 * @param width Output for width; may be NULL.
 * @param height Output for height; may be NULL.
 * @param channels Output for number of channels -- 1 or 3; may be NULL. An alpha channel is
 *        resolved at load time (ph_context_set_alpha_mode()) and never stored.
 * @ingroup context
 */
PH_API void ph_context_get_dimensions(const ph_context_t *ctx, int *width, int *height,
                                      int *channels);

/**
 * @brief Checks if an image is currently loaded in the context.
 * @return 1 if loaded, 0 otherwise (including for a NULL @p ctx).
 * @ingroup context
 */
PH_API int ph_is_loaded(const ph_context_t *ctx);

// --- Loading ---

/**
 * @brief Loads an image from a file path.
 *
 * The file is opened once and its whole content handed to the decoder, memory-mapped
 * where the platform supports it and read into a buffer otherwise; from there the call
 * behaves exactly like ph_load_from_memory() on the same bytes. Peak memory includes the
 * encoded file as well as the decoded image. Any image already loaded is dropped before
 * the file is opened, so a load that fails on the file or its contents leaves the context
 * empty. See docs/guide/loading.md.
 *
 * @param ctx The context.
 * @param filepath Path to the image file.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for a NULL argument;
 *         @c PH_ERR_IO if the path cannot be opened or is not a readable,
 *         non-empty regular file; @c PH_ERR_ALLOCATION_FAILED if the file cannot be
 *         read into memory; otherwise the decoding errors of @c ph_load_from_memory():
 *         @c PH_ERR_UNSUPPORTED_FORMAT, @c PH_ERR_CORRUPT_DATA,
 *         @c PH_ERR_DECODER_UNAVAILABLE, @c PH_ERR_IMAGE_TOO_LARGE and
 *         @c PH_ERR_ALLOCATION_FAILED.
 * @ingroup loading
 */
PH_NODISCARD PH_API ph_error_t ph_load_from_file(ph_context_t *ctx, const char *filepath);

/**
 * @brief Loads an image from an encoded file held in memory.
 *
 * The first bytes choose the decoder. Any image already loaded is dropped before the
 * bytes are decoded, so a load that fails on them leaves the context empty. The formats
 * each build reads are listed in docs/guide/loading.md.
 *
 * @note An animated GIF loads as its first frame. An animated WebP fails with
 *       @c PH_ERR_CORRUPT_DATA: libwebp's simple decode API, which the library uses,
 *       cannot read a frame out of an animation.
 * @note A truncated JPEG, PNG or WebP fails with @c PH_ERR_CORRUPT_DATA in every build:
 *       the data must reach the file's own end (the JPEG end-of-image marker, the PNG
 *       @c IEND chunk, the size its WebP RIFF header states). Bytes after that end are
 *       ignored.
 * @note The encoded data may be at most @c INT_MAX bytes (2 GiB - 1).
 *
 * @param ctx The context.
 * @param buffer Pointer to the raw file data (e.g., JPEG bytes).
 * @param length Size of the buffer.
 * @return @c PH_SUCCESS, or:
 * - @c PH_ERR_INVALID_ARGUMENT for a NULL @p ctx or @p buffer, or a zero @p length;
 * - @c PH_ERR_UNSUPPORTED_FORMAT if the bytes are in no format the library recognizes;
 * - @c PH_ERR_CORRUPT_DATA if the format is recognized but the data is malformed or
 *   truncated;
 * - @c PH_ERR_DECODER_UNAVAILABLE if the format is recognized but this build has no
 *   decoder for it;
 * - @c PH_ERR_IMAGE_TOO_LARGE if the image exceeds the context's @c max_pixels or a fixed
 *   limit, or @p length exceeds @c INT_MAX;
 * - @c PH_ERR_ALLOCATION_FAILED if the decoded image, or its EXIF orientation, does not
 *   fit in memory.
 * @ingroup loading
 */
PH_NODISCARD PH_API ph_error_t ph_load_from_memory(ph_context_t *ctx, const uint8_t *buffer,
                                                   size_t length);

/**
 * @brief Loads an image from an already-decoded pixel buffer.
 *
 * Copies pixels that already live in memory, a frame another library decoded, without an
 * encode and decode in between. The channels are read in the order R, G, B (and A); a
 * buffer in BGR order hashes as a different image. An alpha channel is resolved as
 * ph_context_set_alpha_mode() says, and no orientation is applied. See
 * docs/guide/loading.md.
 *
 * @param ctx The context.
 * @param pixels Pointer to the raw pixel data, `height` rows of `channels`-interleaved bytes.
 * @param width Image width in pixels. Must be > 0.
 * @param height Image height in pixels. Must be > 0.
 * @param channels Number of channels per pixel. Must be 1, 3, or 4; 4 is RGBA, with
 *        straight (not premultiplied) alpha, resolved as ph_context_set_alpha_mode() says.
 * @param stride Number of bytes between the start of consecutive rows. Pass 0 for
 *               tightly packed rows (stride = width * channels).
 * @return @c PH_SUCCESS; @c PH_ERR_INVALID_ARGUMENT for a NULL argument, a value outside
 *         the ranges above, or a @p stride that is negative or shorter than a row;
 *         @c PH_ERR_IMAGE_TOO_LARGE if the image exceeds the context's @c max_pixels;
 *         @c PH_ERR_ALLOCATION_FAILED if the copy does not fit in memory. On any error the
 *         previously loaded image stays loaded.
 * @ingroup loading
 */
PH_NODISCARD PH_API ph_error_t ph_load_from_pixels(ph_context_t *ctx, const uint8_t *pixels,
                                                   int width, int height, int channels, int stride);

// --- uint64_t Hash Algorithms ---

/**
 * @name The four 64-bit hashes
 *
 * The four algorithms below share one contract. Each hashes the image loaded into
 * `ctx` into all 64 bits of `out_hash`, compared with ph_hamming_distance() or
 * ph_similarity(). The value depends on the decoded pixels and on the context's settings
 * -- the grayscale weights, and everything that shapes the pixels at load time
 * (decode scale, auto-orientation, alpha mode) -- so hashes are comparable only between
 * contexts configured alike. The cost grows with the source image's pixel count: the
 * reduction to the hash's working size reads every pixel. Return values:
 *   - @c PH_SUCCESS, with the hash in `out_hash`;
 *   - @c PH_ERR_INVALID_ARGUMENT for a NULL `ctx` or `out_hash`;
 *   - @c PH_ERR_EMPTY_IMAGE if no image is loaded (see ph_is_loaded());
 *   - @c PH_ERR_ALLOCATION_FAILED if the working buffers cannot be allocated.
 *
 * `out_hash` is written only on success. ph_compute_multi() computes any combination
 * of the four in one call.
 * @{
 */

/**
 * @brief Average hash: one bit per cell of an 8x8 grayscale reduction, set where the
 *        cell is at or above the reduction's mean.
 *
 * What moves it and what does not, measured: docs/theory/ahash.md.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT, @c PH_ERR_EMPTY_IMAGE or
 *         @c PH_ERR_ALLOCATION_FAILED, as the shared contract above says.
 * @ingroup hash64
 */
PH_NODISCARD PH_API ph_error_t ph_compute_ahash(ph_context_t *ctx, uint64_t *out_hash);

/**
 * @brief Difference hash: a 9x8 grayscale reduction, one bit per pair of horizontal
 *        neighbors, set where the left one is darker.
 *
 * What moves it and what does not, measured: docs/theory/dhash.md.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT, @c PH_ERR_EMPTY_IMAGE or
 *         @c PH_ERR_ALLOCATION_FAILED, as the shared contract above says.
 * @ingroup hash64
 */
PH_NODISCARD PH_API ph_error_t ph_compute_dhash(ph_context_t *ctx, uint64_t *out_hash);

/**
 * @brief Perceptual (DCT) hash: the low-frequency block of the 2-D DCT of a grayscale
 *        reduction, thresholded at its median plus 0.1% of the AC range.
 *
 * Sizes from ph_context_set_phash_params() (default: a 32x32 reduction, an 8x8 block). With
 * a block smaller than 8x8 only its `reduction_size` squared low bits are used. The DC
 * coefficient's bit is set for any ordinary image, as in pHash. See docs/theory/phash.md.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT, @c PH_ERR_EMPTY_IMAGE or
 *         @c PH_ERR_ALLOCATION_FAILED, as the shared contract above says.
 * @ingroup hash64
 */
PH_NODISCARD PH_API ph_error_t ph_compute_phash(ph_context_t *ctx, uint64_t *out_hash);

/**
 * @brief Wavelet hash: the low-frequency Haar band of a grayscale reduction, thresholded
 *        at its median.
 *
 * The scale and depth come from ph_context_set_whash_mode(); the coarsest band can be
 * zeroed with ph_context_set_whash_remove_max_haar_ll(). What the band amounts to, and
 * what moves the hash, measured: docs/theory/whash.md.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT, @c PH_ERR_EMPTY_IMAGE or
 *         @c PH_ERR_ALLOCATION_FAILED, as the shared contract above says.
 * @ingroup hash64
 */
PH_NODISCARD PH_API ph_error_t ph_compute_whash(ph_context_t *ctx, uint64_t *out_hash);
/** @} */

/**
 * @brief Flags selecting which uint64_t hash algorithms to compute in a single
 *        `ph_compute_multi()` call. Bitwise-OR any combination.
 * @ingroup hash64
 */
typedef enum {
    PH_HASH_AHASH = 1 << 0,
    PH_HASH_DHASH = 1 << 1,
    PH_HASH_PHASH = 1 << 2,
    PH_HASH_WHASH = 1 << 3,
    /* Only the four uint64_t algorithms are flags. Every other algorithm returns a
     * digest and is computed with its own ph_compute_* function or ph_compute_digest().
     * Bits 4 and up are not valid flags. */
    PH_HASH_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not a flag -- see "Enum width".
} ph_hash_flags_t;

/** Number of distinct bits defined in ph_hash_flags_t. Sizes ph_compute_multi's out[].
 * @ingroup hash64 */
#define PH_HASH_FLAGS_COUNT 4

/**
 * @brief Computes multiple uint64_t hash algorithms for the loaded image in one call.
 *
 * Equivalent to calling the individual `ph_compute_*` functions for each flag set in
 * `flags`. The work over the full image is cached on the context and done once, whichever
 * algorithms ask for it: the grayscale conversion, and one area-average pass that aHash,
 * pHash (at the default `dct_size`) and wHash (`PH_WHASH_FAST`) all reduce from -- BMH
 * shares it too. dHash resamples on its own. On a 20-megapixel image the four together
 * cost about half of what four independent resizes would.
 * Results are bit-for-bit identical to calling the equivalent `ph_compute_*` function
 * directly.
 *
 * Computation stops at the first algorithm that fails and its error code is returned.
 *
 * On such a failure @p out is left partially written: the slots of the algorithms that
 * ran before the failing one hold their correct hashes, and the failing algorithm's slot
 * and every slot after it are untouched — not zeroed. There is no way to tell how far it
 * got from @p out alone, so a caller that gets a non-@c PH_SUCCESS return must treat the
 * whole array as unusable, or re-request the algorithms it still wants one at a time.
 * On @c PH_SUCCESS exactly as many slots as there are bits in @p flags are written, and
 * nothing beyond them is ever touched.
 *
 * @param ctx The context. Must have an image already loaded, or the call returns
 *            @c PH_ERR_EMPTY_IMAGE.
 * @param flags Bitwise-OR of `ph_hash_flags_t` values selecting which hashes to compute.
 * @param[out] out Array written with one uint64_t per flag that was set, in ascending
 *                 bit order (e.g. for `PH_HASH_DHASH | PH_HASH_WHASH`, `out[0]` receives
 *                 the dHash and `out[1]` the wHash). Must have room for at least as many
 *                 elements as bits set in `flags` (at most `PH_HASH_FLAGS_COUNT`).
 * @return @c PH_SUCCESS; @c PH_ERR_INVALID_ARGUMENT for a NULL @p ctx or @p out, or
 *         @p flags that are zero or hold a bit no ph_hash_flags_t value defines;
 *         @c PH_ERR_EMPTY_IMAGE if no image is loaded; @c PH_ERR_ALLOCATION_FAILED from
 *         the algorithm that failed.
 * @ingroup hash64
 */
PH_NODISCARD PH_API ph_error_t ph_compute_multi(ph_context_t *ctx, uint32_t flags, uint64_t out[]);

// --- Batch Hashing ---

/** Number of hash slots in each batch item's `hashes[]` array.
 *
 * Deliberately separate from @c PH_HASH_FLAGS_COUNT, which only says how many algorithms
 * are defined today. The array size is part of the batch structs' layout, and so of the
 * ABI; tying it to the flag count would mean a new uint64_t algorithm moves `status` and
 * changes the struct size. The spare slots are that headroom: up to four new uint64_t
 * algorithms can be added without an ABI break. On a per-item success the first
 * popcount(flags) slots are written and the rest are left untouched; on a per-item
 * failure every slot is zeroed. @ingroup batch */
#define PH_BATCH_HASHES_CAPACITY 8

/**
 * @brief One entry in a `ph_hash_files()` batch: a file path in, hashes and status out.
 * @ingroup batch
 */
typedef struct {
    const char *path; ///< Path to the image file to hash. Must stay valid for the call.
    /** [out] One uint64_t per flag set in the `flags` passed to `ph_hash_files()`, packed
     *  in ascending bit order -- same layout as `ph_compute_multi()`'s `out[]`. Valid only
     *  if `status == PH_SUCCESS`. */
    uint64_t hashes[PH_BATCH_HASHES_CAPACITY];
    ph_error_t status; ///< [out] Per-item result. A failure here does not abort the batch.
} ph_batch_item_t;

/**
 * @brief One entry in a `ph_hash_buffers()` batch: an in-memory image buffer in, hashes
 *        and status out.
 * @ingroup batch
 */
typedef struct {
    const uint8_t *buffer; ///< Pointer to the encoded image bytes (e.g. JPEG/PNG/WebP).
    size_t length;         ///< Size of `buffer` in bytes.
    /** [out] One uint64_t per flag set in the `flags` passed to `ph_hash_buffers()`, packed
     *  in ascending bit order -- same layout as `ph_compute_multi()`'s `out[]`. Valid only
     *  if `status == PH_SUCCESS`. */
    uint64_t hashes[PH_BATCH_HASHES_CAPACITY];
    ph_error_t status; ///< [out] Per-item result. A failure here does not abort the batch.
} ph_batch_buffer_item_t;

/**
 * @brief Hashes a batch of image files, optionally across a pool of internal threads.
 *
 * Each item is loaded and hashed independently. Internally this calls the same
 * `ph_compute_multi()` used for a single image: the file is decoded once, converted to
 * grayscale once and reduced by one shared area-average pass, whatever the flags; dHash
 * adds a resampling pass of its own. A decode/hash failure on one
 * item is recorded in that item's `status` and does not stop the rest of the batch from being
 * processed.
 *
 * This is ph_hash_files_ex() with every option at its default, and three of those
 * defaults matter:
 *
 * - **Default configuration.** Every item is hashed as by a freshly created context:
 *   nothing set with a `ph_context_set_*` function applies, so for a context whose
 *   configuration you changed, the batch and the single-image path give *different*
 *   hashes for the same file. That includes `max_pixels`, the decompression-bomb guard:
 *   the batch uses the default limit (see ph_context_set_max_pixels()), not a stricter
 *   one you set elsewhere. Pass a configured context through ph_hash_files_ex() instead.
 * - **Blocking and not cancellable.** The call returns only after the last item, and
 *   reports no progress. To bound the time, split the list yourself, or use
 *   ph_hash_files_ex() with a `should_continue` callback.
 * - **Peak memory grows with the thread count.** Each worker holds one decoded image at a
 *   time -- its RGB pixels plus a grayscale copy, about 4 bytes per pixel -- so the peak
 *   is roughly `workers x 4 x the largest image's pixel count`. At the default
 *   `max_pixels` limit that is up to about 1 GB per worker, and `threads = 0` starts one
 *   worker per core: on a 64-core machine, images near that limit can need 64 GB.
 *   Measured: 20-megapixel JPEGs take about 80 MB per worker. Cap it by passing an
 *   explicit thread count, a lower `max_pixels` through ph_hash_files_ex(), or both.
 *
 * Return contract -- the overall return value reports only failures that stopped the batch
 * from being *worked on at all*; anything that happened to an individual image is in that
 * item's `status` and never in the return value:
 *
 * - `PH_ERR_INVALID_ARGUMENT` -- malformed call, nothing was written. `flags` is zero or
 *   contains an unknown bit, `threads` is negative, or `items` is NULL with `n > 0`.
 *   Validated *before* `n` is looked at, so an empty batch does not excuse a bad argument:
 *   `ph_hash_files(NULL, 0, 0, -5)` returns `PH_ERR_INVALID_ARGUMENT`, not `PH_SUCCESS`.
 * - `PH_SUCCESS` with `n == 0` -- no-op. `items` may be NULL in this case.
 * - `PH_ERR_ALLOCATION_FAILED` -- the batch could not be worked on: no internal context or
 *   worker could be created, so not one item was looked at and all of them are left at
 *   `PH_ERR_ALLOCATION_FAILED`. This covers the sequential path failing to allocate its
 *   context, failing to allocate the worker array, failing to create any thread, and every
 *   created thread bailing out because it could not allocate its own context. Partial
 *   degradation is *not* reported here: if even one worker starts it processes the whole
 *   batch by itself and the call returns `PH_SUCCESS`.
 * - `PH_SUCCESS` otherwise -- the batch was processed to the end. This says nothing about
 *   whether any individual image succeeded; inspect every `items[i].status`.
 *
 * @param items Array of batch entries; `path`/`hashes`/`status` are read/written in place.
 * @param n Number of entries in `items`. 0 is a no-op that returns PH_SUCCESS, provided
 *          `flags` and `threads` are themselves valid.
 * @param flags Bitwise-OR of `ph_hash_flags_t` values selecting which algorithms to
 *              compute for every item. See `ph_compute_multi()` for the `hashes[]`
 *              packing convention.
 * @param threads Worker thread count. 0 = one per CPU this process may use (see below),
 *                1 = run sequentially on the calling thread with no thread creation,
 *                >1 = that many workers.
 *                Never more workers than items: a count above `n` runs `n` workers.
 *                Ignored (always sequential) if the library was built without
 *                `PHASH_ENABLE_THREADS` (ON by default in both CMake and the Makefile).
 *
 *                What `threads = 0` counts: the online CPUs, narrowed on Linux by the
 *                process's affinity mask (`taskset`, `docker --cpuset-cpus`) and by a cgroup
 *                v1/v2 CPU quota rounded up (`docker --cpus`, Kubernetes CPU limits), and on
 *                Windows by the process affinity mask. macOS has neither and uses the
 *                online count.
 *
 *                Platform note for `threads = 0`: on POSIX the count can reach every
 *                online CPU, but on Windows it covers only the *current processor group*,
 *                which the OS caps at 64 logical processors. On a machine with more than
 *                that (large servers, some CI runners) `threads = 0` therefore uses at most
 *                64 workers on Windows while the POSIX build uses all of them. This is a
 *                deliberate limitation, not an oversight: raising the count alone would not
 *                help, because a thread inherits its creator's processor group and the extra
 *                workers would contend for the same 64 logical processors. Spreading workers
 *                across groups needs explicit group affinity and is not implemented. If you
 *                need more than 64 workers on such a machine, pass the count explicitly and
 *                set the affinity yourself.
 * @return @c PH_SUCCESS once the batch has been processed (regardless of per-item
 *         outcomes), @c PH_ERR_INVALID_ARGUMENT for a malformed call, or
 *         @c PH_ERR_ALLOCATION_FAILED if no item could be worked on at all. See the return
 *         contract above.
 * @ingroup batch
 */
PH_NODISCARD PH_API ph_error_t ph_hash_files(ph_batch_item_t *items, size_t n, uint32_t flags,
                                             int threads);

/**
 * @brief Same as `ph_hash_files()`, but for already-in-memory encoded image buffers
 *        (e.g. downloaded bytes) instead of file paths.
 *
 * Identical semantics and identical return contract, including validation running before
 * the `n == 0` shortcut: `ph_hash_buffers(NULL, 0, 0, -5)` returns PH_ERR_INVALID_ARGUMENT.
 * An entry whose `buffer` is NULL or whose `length` is 0 is a per-item
 * PH_ERR_INVALID_ARGUMENT in `status`, not an overall failure. The `threads = 0` platform
 * note from `ph_hash_files()` applies here unchanged: on Windows the auto-detected count is
 * limited to the current processor group's 64 logical processors. So do its three notes on
 * defaults -- default configuration, no cancellation, memory per worker -- and
 * ph_hash_buffers_ex() is the way around them. The encoded buffers themselves are the
 * caller's and are not copied, so they add nothing per worker.
 * @return As ph_hash_files(): @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT or
 *         @c PH_ERR_ALLOCATION_FAILED.
 * @ingroup batch
 */
PH_NODISCARD PH_API ph_error_t ph_hash_buffers(ph_batch_buffer_item_t *items, size_t n,
                                               uint32_t flags, int threads);

/**
 * @brief Called before a batch worker starts each item; return 0 to stop the batch.
 *
 * Called from worker threads -- possibly several at once -- so it must be thread-safe;
 * typically it reads an atomic flag or a deadline. After it returns 0 once, no worker
 * starts another item, items already in progress finish normally, and every item not
 * started gets @c PH_ERR_CANCELLED. It may still be called a few more times by workers
 * that had not yet seen the stop.
 * @ingroup batch
 */
typedef int (*ph_batch_continue_fn)(void *user_data);

/**
 * @brief Called after a batch worker finishes an item, successfully or not.
 *
 * @p done counts finished items: each value from 1 up to the number of items finished
 * is passed exactly once, but calls come from worker threads, possibly concurrently and
 * not in order, so it must be thread-safe. @p total is the batch size. Not called for
 * items skipped by a cancellation.
 * @ingroup batch
 */
typedef void (*ph_batch_progress_fn)(size_t done, size_t total, void *user_data);

/**
 * @brief Options for ph_hash_files_ex() and ph_hash_buffers_ex().
 *
 * Initialize with ph_batch_options_init(), then set the fields you need: that fills in
 * @c struct_size and the defaults, and keeps working when later versions append fields.
 * A caller that fills the struct by hand must set @c struct_size to sizeof of the struct
 * it was compiled with.
 * @ingroup batch
 */
typedef struct {
    /** sizeof(ph_batch_options_t) as the caller compiled it. Lets a later version add
     *  fields at the end and still accept a struct from an older caller. */
    size_t struct_size;
    /** Configuration template, or NULL for the defaults. Everything set on it with a
     *  `ph_context_set_*` function -- including `max_pixels` -- is copied into every
     *  worker's own context, so the batch hashes each item exactly as ph_load_from_file()
     *  + ph_compute_multi() on this context would. It is read once, on the calling
     *  thread, before any worker starts; an image loaded on it is ignored. */
    const ph_context_t *config;
    /** Worker count, as in ph_hash_files(): 0 = one per usable CPU, 1 = sequential on
     *  the calling thread, >1 = that many. Default 0. */
    int threads;
    /** Optional; NULL never stops. See ph_batch_continue_fn. */
    ph_batch_continue_fn should_continue;
    /** Optional; NULL reports nothing. See ph_batch_progress_fn. */
    ph_batch_progress_fn on_progress;
    /** Passed unchanged to both callbacks. */
    void *user_data;
} ph_batch_options_t;

/**
 * @brief Fills @p options with the defaults and the right @c struct_size.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for a NULL @p options.
 * @ingroup batch
 */
PH_API ph_error_t ph_batch_options_init(ph_batch_options_t *options);

/**
 * @brief ph_hash_files() with options: a configuration template, cancellation and
 *        progress.
 *
 * Same items, flags, per-item statuses and validation as ph_hash_files(). @p options may
 * be NULL, which means every default -- the call is then ph_hash_files() with
 * `threads = 0`. With a configuration template the peak-memory note on ph_hash_files()
 * applies with that template's `max_pixels` as the bound.
 *
 * @return
 * - `PH_ERR_INVALID_ARGUMENT`: as ph_hash_files(), or @c struct_size smaller than any
 *   version of the struct, or a negative @c threads; nothing was written.
 * - `PH_ERR_ALLOCATION_FAILED`: as ph_hash_files() -- no item was worked on.
 * - `PH_ERR_CANCELLED`: @c should_continue stopped the batch before every item was
 *   started. The items that were started have their real status; the rest have
 *   @c PH_ERR_CANCELLED and zeroed hashes.
 * - `PH_SUCCESS`: every item was processed; inspect each `status`.
 * @ingroup batch
 */
PH_NODISCARD PH_API ph_error_t ph_hash_files_ex(ph_batch_item_t *items, size_t n, uint32_t flags,
                                                const ph_batch_options_t *options);

/**
 * @brief ph_hash_buffers() with options; see ph_hash_files_ex().
 * @return As ph_hash_files_ex(): @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT,
 *         @c PH_ERR_ALLOCATION_FAILED or @c PH_ERR_CANCELLED.
 * @ingroup batch
 */
PH_NODISCARD PH_API ph_error_t ph_hash_buffers_ex(ph_batch_buffer_item_t *items, size_t n,
                                                  uint32_t flags,
                                                  const ph_batch_options_t *options);

// --- Algorithms as values ---

/**
 * @brief Every hash algorithm, as a value -- for code that picks the algorithm at run time
 * (a binding, a configuration file, a database column) instead of calling one of the
 * ph_compute_* functions by name.
 *
 * The values are contiguous from 0 to @c PH_ALGORITHM_COUNT - 1, so `for (a = 0; a <
 * PH_ALGORITHM_COUNT; a++)` visits every algorithm. For the four uint64_t algorithms the
 * matching ph_hash_flags_t bit is `1u << value`: @c PH_HASH_DHASH == 1u << @c PH_ALGO_DHASH.
 * New algorithms are appended; existing values never change.
 * @ingroup algorithms
 */
typedef enum {
    PH_ALGO_AHASH = 0,         ///< ph_compute_ahash(); "ahash".
    PH_ALGO_DHASH = 1,         ///< ph_compute_dhash(); "dhash".
    PH_ALGO_PHASH = 2,         ///< ph_compute_phash(); "phash".
    PH_ALGO_WHASH = 3,         ///< ph_compute_whash(); "whash".
    PH_ALGO_BMH = 4,           ///< ph_compute_bmh(); "bmh".
    PH_ALGO_MHASH = 5,         ///< ph_compute_mhash(); "mhash".
    PH_ALGO_RADIAL = 6,        ///< ph_compute_radial_hash(); "radial".
    PH_ALGO_COLOR_HASH = 7,    ///< ph_compute_color_hash(); "color_hash".
    PH_ALGO_COLOR_MOMENTS = 8, ///< ph_compute_color_moments_hash(); "color_moments".
    PH_ALGO_FORCE_INT32_ = PH_ENUM_FORCE_INT32_VALUE, ///< Not an algorithm -- see "Enum width".
} ph_algorithm_t;

/** Number of ph_algorithm_t values: every algorithm is in [0, PH_ALGORITHM_COUNT).
 * @ingroup algorithms */
#define PH_ALGORITHM_COUNT 9

/**
 * @brief Computes any algorithm's hash into a digest.
 *
 * Exactly the result of the algorithm's own ph_compute_* function, same errors included
 * (@c PH_ERR_EMPTY_IMAGE, @c PH_ERR_REQUIRES_COLOR, ...). The four uint64_t algorithms
 * come back as an 8-byte @c PH_DIGEST_KIND_BITS digest holding the hash most significant
 * byte first -- the order ph_hash_to_hex() writes -- so ph_hamming_distance_digest() on
 * two of them equals ph_hamming_distance() on the two hashes, and every algorithm can be
 * stored and compared through the digest functions alone.
 *
 * @param ctx The context, with an image loaded.
 * @param algo The algorithm.
 * @param[out] out_digest Receives the digest; its size and kind are what ph_digest_info()
 *                        reports for this context and algorithm.
 * @return As the algorithm's ph_compute_* function -- @c PH_SUCCESS,
 *         @c PH_ERR_INVALID_ARGUMENT, @c PH_ERR_EMPTY_IMAGE, @c PH_ERR_REQUIRES_COLOR or
 *         @c PH_ERR_ALLOCATION_FAILED -- and @c PH_ERR_INVALID_ARGUMENT for an @p algo that
 *         is not a ph_algorithm_t value.
 * @ingroup algorithms
 */
PH_NODISCARD PH_API ph_error_t ph_compute_digest(ph_context_t *ctx, ph_algorithm_t algo,
                                                 ph_digest_t *out_digest);

/**
 * @brief Tells what digest an algorithm produces, without an image and without computing
 * anything: its size in bytes and its kind (which decides the comparison metric).
 *
 * The answer comes from the same code that sets the size and kind of every computed digest,
 * so it cannot disagree with ph_compute_digest() or the ph_compute_* functions. Only BMH's
 * size depends on the configuration (ph_context_set_block_params()); the others are fixed.
 *
 * @param ctx The configuration to answer for, or NULL for the defaults. Its image, if any,
 *            is not looked at.
 * @param algo The algorithm.
 * @param[out] out_size Receives the digest size in bytes (8 for the uint64_t algorithms, as
 *                      ph_compute_digest() returns them). May be NULL.
 * @param[out] out_kind Receives the digest kind. May be NULL.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for an @p algo that is not a
 *         ph_algorithm_t value (nothing is written then).
 * @ingroup algorithms
 */
PH_NODISCARD PH_API ph_error_t ph_digest_info(const ph_context_t *ctx, ph_algorithm_t algo,
                                              size_t *out_size, ph_digest_kind_t *out_kind);

/**
 * @brief The algorithm's stable lowercase name: "ahash", "dhash", "phash", "whash", "bmh",
 * "mhash", "radial", "color_hash", "color_moments".
 * @return A static string, never NULL; "unknown" for a value that is not an algorithm.
 * @ingroup algorithms
 */
PH_API const char *ph_algorithm_name(ph_algorithm_t algo);

/**
 * @brief The inverse of ph_algorithm_name(): exact, lowercase match.
 * @param name The name.
 * @param[out] out_algo Receives the algorithm. Untouched on error.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for a NULL argument or a name that
 *         is not one ph_algorithm_name() returns.
 * @ingroup algorithms
 */
PH_NODISCARD PH_API ph_error_t ph_algorithm_from_name(const char *name, ph_algorithm_t *out_algo);

// --- Digest Hash Algorithms ---

/**
 * @brief Computes Block Mean Hash (BMH). Returns a `block_size * block_size`-bit digest
 * (256 bits / 32 bytes at the default block_size 16; see ph_context_set_block_params()).
 * See docs/theory/bmh.md.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT for a NULL argument,
 *         @c PH_ERR_EMPTY_IMAGE if no image is loaded, or @c PH_ERR_ALLOCATION_FAILED.
 * @ingroup digests
 */
PH_NODISCARD PH_API ph_error_t ph_compute_bmh(ph_context_t *ctx, ph_digest_t *out_digest);

/**
 * @brief Computes the color moments hash. Returns an 18-byte digest.
 *
 * The mean, the standard deviation and the cube root of the third central moment of each
 * of the R, G and B channels, after Stricker & Orengo (1995): nine signed 16-bit
 * big-endian numbers in units of 1/@c PH_VECTOR16_SCALE of a channel level. Compare with
 * ph_l2_distance(), not with the bit metrics. See docs/theory/color-moments.md.
 *
 * Requires a color image: the loaded image must have at least 3 channels. On a
 * single-channel image — one loaded while ph_context_set_load_grayscale() was
 * enabled, or handed to ph_load_from_pixels() with @c channels = 1 — this returns
 * @c PH_ERR_REQUIRES_COLOR and leaves @p out_digest untouched.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT for a NULL argument,
 *         @c PH_ERR_EMPTY_IMAGE if no image is loaded, or @c PH_ERR_REQUIRES_COLOR.
 * @ingroup digests
 */
PH_NODISCARD PH_API ph_error_t ph_compute_color_moments_hash(ph_context_t *ctx,
                                                             ph_digest_t *out_digest);

/**
 * @brief Computes the color histogram hash. Returns a 108-byte digest.
 *
 * The image's pixels are counted into 108 bins of the opponent color space — red against
 * green, blue against yellow, light against dark, at 6 x 6 x 3 — and each bin is scaled
 * against the largest. This is a color histogram with histogram intersection, after
 * Swain & Ballard (1991), implemented from secondary descriptions of the paper; no
 * conformance to the paper itself is claimed. The quantization is
 * this library's own, chosen by measurement.
 *
 * Compare with ph_histogram_intersection(), not with the bit or vector metrics.
 *
 * Requires a color image: the loaded image must have at least 3 channels. On a
 * single-channel image — one loaded while ph_context_set_load_grayscale() was enabled, or
 * handed to ph_load_from_pixels() with @c channels = 1 — this returns
 * @c PH_ERR_REQUIRES_COLOR and leaves @p out_digest untouched.
 *
 * @note Like every color histogram it discards spatial layout entirely: an image and a
 *       shuffling of its pixels hash identically. Use it alongside a structural hash, not
 *       instead of one. See docs/theory/color-hash.md.
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT for a NULL argument,
 *         @c PH_ERR_EMPTY_IMAGE if no image is loaded, or @c PH_ERR_REQUIRES_COLOR.
 * @ingroup digests
 */
PH_NODISCARD PH_API ph_error_t ph_compute_color_hash(ph_context_t *ctx, ph_digest_t *out_digest);

/**
 * @brief Computes the Marr-Hildreth hash. Returns a 72-byte (576-bit) digest.
 *
 * The image is blurred at sigma 1, normalized to `size` x `size` (512 by default) and
 * histogram-equalized over 256 levels; the Laplacian-of-Gaussian operator of Marr and
 * Hildreth (alpha = 2, level = 1 by default; see ph_context_set_mhash_params()) is
 * correlated with it; the response is summed into a 31x31 grid of blocks (16x16 pixels
 * at the default size); and
 * nine bits are emitted per 3x3 window of that grid at stride 4, each thresholded against
 * its window's mean. That construction is pHash's `ph_mh_imagehash()`, which is its
 * primary source — there is no paper for it. Values are close in spirit but not identical
 * to pHash's; see docs/algorithm-provenance.md section 5.
 *
 * The digest is a bit vector: compare it with ph_hamming_distance_digest() or
 * ph_similarity_digest(). See docs/theory/mhash.md.
 *
 * @return @c PH_SUCCESS, @c PH_ERR_INVALID_ARGUMENT for a NULL argument,
 *         @c PH_ERR_EMPTY_IMAGE if no image is loaded, or @c PH_ERR_ALLOCATION_FAILED.
 * @ingroup digests
 */
PH_NODISCARD PH_API ph_error_t ph_compute_mhash(ph_context_t *ctx, ph_digest_t *out_digest);

/**
 * @brief Computes the Radial variance hash. Returns a 40-byte digest.
 *
 * The variance of the pixels along each of `radial_projections` lines through the image
 * center (default 180, one per degree), reduced by a 1-D DCT to its first 40
 * coefficients, which are quantized into the digest. Uses the context gamma, and nothing
 * else does.
 *
 * An image with no angular structure -- blank, or with nearly the same variance along
 * every line, as a radially symmetric one has -- gets an all-zero digest and
 * @c PH_SUCCESS; ph_radial_similarity() answers any comparison with it by
 * @c PH_ERR_NO_STRUCTURE.
 *
 * @warning Compare these digests with ph_radial_similarity(), not with
 *          ph_hamming_distance_digest(), ph_l2_distance() or ph_similarity_digest(): the
 *          bytes are quantized coefficients, not bits or a point in space. The digest
 *          tolerates a rotation of a few degrees and an exact half turn, not an arbitrary
 *          one. See docs/theory/radial.md.
 * @return @c PH_SUCCESS (the all-zero digest included), @c PH_ERR_INVALID_ARGUMENT for a
 *         NULL argument, @c PH_ERR_EMPTY_IMAGE if no image is loaded, or
 *         @c PH_ERR_ALLOCATION_FAILED.
 * @ingroup digests
 */
PH_NODISCARD PH_API ph_error_t ph_compute_radial_hash(ph_context_t *ctx, ph_digest_t *out_digest);

// --- Comparison Functions ---

/**
 * @brief Number of differing bits between two 64-bit hashes, 0 to 64.
 *
 * For aHash, dHash, pHash and wHash values. Only meaningful between two hashes of the same
 * algorithm, computed with the same settings.
 * @ingroup compare
 */
PH_API int ph_hamming_distance(uint64_t hash1, uint64_t hash2);

/**
 * @brief Normalized similarity between two 64-bit hashes, in [0.0, 1.0].
 *
 * 1.0 means identical hashes, 0.0 means every bit differs, and two unrelated images land
 * near 0.5. The scale is shared with ph_similarity_digest() for digests of any length; a
 * threshold is not, since how close a copy comes depends on the algorithm. See
 * docs/theory/comparing.md.
 * @ingroup compare
 */
PH_API double ph_similarity(uint64_t a, uint64_t b);

/**
 * @name Comparing digests
 *
 * The contract shared by every function below that reads a ph_digest_t.
 *
 * ph_digest_t is a flat struct callers (including FFI bindings) may fill in
 * themselves, and `size` can hold values `data` cannot: a digest whose `size`
 * exceeds PH_DIGEST_MAX_BYTES is rejected, never truncated.
 *
 * The `kind` tag is checked too. Each comparison below states the kind it
 * is for, and refuses a digest tagged as something else: Hamming distance over
 * quantized DCT coefficients returns a plausible number that means nothing, and this
 * is how that call fails instead. PH_DIGEST_KIND_UNSPECIFIED -- the zero a hand-filled
 * struct holds -- is accepted everywhere, so a binding that does not set the field gets
 * no protection but no error either. A digest that breaks the contract gets:
 *
 *   - functions returning ph_error_t: PH_ERR_INVALID_ARGUMENT;
 *   - distance/similarity functions: -1 (also for a size of 0, which carries no
 *     bits to compare -- reporting distance 0 there would read as "identical").
 *
 * ph_hamming_distance_digest() and ph_similarity_digest() are for
 * PH_DIGEST_KIND_BITS; ph_l2_distance() is for PH_DIGEST_KIND_VECTOR and
 * PH_DIGEST_KIND_VECTOR16; ph_radial_similarity() is for PH_DIGEST_KIND_COEFFICIENTS;
 * ph_histogram_intersection() is for PH_DIGEST_KIND_HISTOGRAM.
 * @{
 */
/**
 * @brief Number of differing bits between two @c PH_DIGEST_KIND_BITS digests (mHash, BMH,
 *        or a 64-bit hash taken as a digest).
 * @return 0 to 8 times the digest size; -1 for anything the digest contract above rejects:
 *         NULL, mismatched or invalid sizes, or another kind.
 * @ingroup compare
 */
PH_API int ph_hamming_distance_digest(const ph_digest_t *a, const ph_digest_t *b);

/**
 * @brief Euclidean distance between two feature vectors: @c PH_DIGEST_KIND_VECTOR16
 *        (ColorMoments, decoded from its 16-bit fixed point) or @c PH_DIGEST_KIND_VECTOR
 *        (one unsigned byte per feature).
 * @return 0.0 or more, in the features' own units; -1.0 for anything the digest contract
 *         above rejects: NULL, mismatched or invalid sizes, or another kind.
 * @ingroup compare
 */
PH_API double ph_l2_distance(const ph_digest_t *a, const ph_digest_t *b);

/**
 * @brief Normalized similarity between two digests, in [0.0, 1.0].
 * @return -1.0 for anything the digest contract above rejects: NULL, mismatched or
 *         invalid sizes, or a kind other than PH_DIGEST_KIND_BITS.
 * @ingroup compare
 */
PH_API double ph_similarity_digest(const ph_digest_t *a, const ph_digest_t *b);

/**
 * @brief The peak-of-cross-correlation threshold the radial hash's source uses, 0.9.
 *
 * pHash treats two radial digests correlating at or above this as the same image
 * (Zauner, Diplomarbeit FH Hagenberg 2010, section 3.2.3). It is provided as a starting
 * point with a citation behind it, not as a tuned recommendation for your corpus:
 * ph_radial_similarity() hands back the raw score precisely so that you can pick your
 * own cut. Do pick it deliberately and measure it — a threshold chosen by eye is the
 * usual reason a perceptual hash "does not work".
 * @ingroup compare
 */
#define PH_RADIAL_PCC_THRESHOLD 0.9

/**
 * @brief Compares two radial digests the way the algorithm's source specifies: by the
 *        peak of their cross-correlation over all cyclic shifts.
 *
 * The Pearson correlation of the two digests' bytes, computed with @p b shifted
 * cyclically by each of 0 to size - 1 places; the largest of them. It runs from -1.0 to
 * 1.0, and 1.0 means the same profile up to a shift. Compare it against
 * @c PH_RADIAL_PCC_THRESHOLD, or against your own measured cut. The score is symmetric in
 * @p a and @p b. See docs/theory/radial.md.
 *
 * A digest with all bytes equal -- the all-zero digest ph_compute_radial_hash() gives an
 * image with no angular structure -- has no correlation with anything: any number would
 * be invented, and 1.0 would call two unrelated flat images identical. Such a pair is
 * answered with @c PH_ERR_NO_STRUCTURE; whether "no data" counts as a match is the
 * caller's decision.
 *
 * @param a,b Digests of equal size and kind @c PH_DIGEST_KIND_COEFFICIENTS (or
 *        unspecified), both valid per the contract above.
 * @param out_pcc Receives the score. Untouched on error.
 * @return @c PH_SUCCESS; @c PH_ERR_NO_STRUCTURE if either digest has all bytes equal;
 *         @c PH_ERR_INVALID_ARGUMENT for a NULL argument, an invalid or empty digest, two
 *         digests of different sizes, or a digest of another kind.
 *
 * @note This returns its result through @p out_pcc rather than as the return value, as
 *       the other comparison functions here do. They signal failure with -1.0, and -1.0
 *       is a legitimate correlation — a perfect anti-correlation — so the sentinel would
 *       be ambiguous exactly where the caller needs it not to be.
 * @ingroup compare
 */
PH_NODISCARD PH_API ph_error_t ph_radial_similarity(const ph_digest_t *a, const ph_digest_t *b,
                                                    double *out_pcc);

/**
 * @brief Compares two color histograms by their intersection: `sum(min(a_i, b_i))` over
 *        bins, each histogram normalized by its own total.
 *
 * The measure Swain & Ballard define, and the reason a histogram is worth keeping: it
 * counts only what the two images have in common, so a change of background or a partial
 * overlap costs only the part that differs.
 *
 * Runs from 0.0 (no color in common) to 1.0 (identical distributions). Two empty
 * histograms score 1.0; an empty one against a populated one scores 0.0.
 *
 * @note Swain & Ballard normalize by the reference histogram, which makes their score
 *       asymmetric when the two images hold different pixel counts. This normalizes each
 *       side by its own total, which agrees with them whenever the counts match and is
 *       symmetric when they do not. See docs/theory/color-hash.md.
 *
 * @param a,b Digests of equal size, both from ph_compute_color_hash() (or untagged).
 * @param out_similarity Receives the score. Untouched on error.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for a NULL argument, an invalid or
 *         empty digest, two digests of different sizes, or a digest tagged as something
 *         other than a histogram.
 * @ingroup compare
 */
PH_NODISCARD PH_API ph_error_t ph_histogram_intersection(const ph_digest_t *a, const ph_digest_t *b,
                                                         double *out_similarity);
/** @} */

/** Buffer size that holds the text form of any digest, terminator included: the longest
 *  kind name plus its colon ("coefficients:", 13 characters), two hex digits per byte of
 *  a full @c PH_DIGEST_MAX_BYTES digest, and the NUL. @ingroup text */
#define PH_DIGEST_HEX_BUFFER_SIZE (13 + PH_DIGEST_MAX_BYTES * 2 + 1)

/**
 * @brief Encodes a digest as text: its kind, a colon, then its bytes in lowercase hex.
 *
 * The kind is the lowercase suffix of its ph_digest_kind_t name -- `unspecified`, `bits`,
 * `coefficients`, `vector`, `histogram`, `vector16` -- so a radial digest reads
 * `coefficients:1f80...`. The bytes follow in order, data[0] first. Carrying the kind is
 * what keeps the comparison functions able to refuse the wrong metric for digests that
 * were stored and read back (see ph_digest_kind_t).
 *
 * @param d Digest to encode.
 * @param out Output buffer. @c PH_DIGEST_HEX_BUFFER_SIZE bytes always suffice.
 * @param out_size Size of 'out' in bytes; at least the kind name's length + 1 +
 *                 d->size * 2 + 1.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT if arguments are invalid, the
 *         digest's kind is not a ph_digest_kind_t value, or @p out_size is too small.
 * @ingroup text
 */
PH_NODISCARD PH_API ph_error_t ph_digest_to_hex(const ph_digest_t *d, char *out, size_t out_size);

/**
 * @brief Decodes the text form produced by ph_digest_to_hex() back into a digest,
 * kind included.
 *
 * The kind prefix is required and must be one of the names ph_digest_to_hex() writes,
 * in lowercase; the hex digits after the colon may be either case. A bare hex string
 * without a prefix is rejected rather than read as an untagged digest: prefix it with
 * `unspecified:` to accept it knowingly, or better, with the kind of the algorithm that produced
 * it.
 *
 * @param text NUL-terminated string `<kind>:<hex>`; the hex part must have an even number
 * of digits and decode to at most PH_DIGEST_MAX_BYTES bytes.
 * @param out Output digest. Untouched on error.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT if @p text is malformed, has no or
 *         an unknown kind prefix, or is too long.
 * @ingroup text
 */
PH_NODISCARD PH_API ph_error_t ph_digest_from_hex(const char *text, ph_digest_t *out);

/**
 * @brief Encodes a 64-bit hash as a fixed 16-character lowercase hex string
 * (big-endian, i.e. the most significant byte comes first).
 * @param hash Hash value to encode.
 * @param out Output buffer.
 * @param out_size Size of 'out' in bytes; must be at least 17.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT if arguments are invalid or
 *         @p out_size is too small.
 * @ingroup text
 */
PH_NODISCARD PH_API ph_error_t ph_hash_to_hex(uint64_t hash, char *out, size_t out_size);

/**
 * @brief Decodes the text ph_hash_to_hex() writes back into a 64-bit hash.
 *
 * Exactly 16 hex digits, most significant byte first, either case; nothing before or
 * after them (no "0x", no whitespace). Unlike the digest text form there is no kind
 * prefix: a uint64_t hash is always a bit vector.
 * @param hex NUL-terminated string of 16 hex digits.
 * @param[out] out Receives the hash. Untouched on error.
 * @return @c PH_SUCCESS, or @c PH_ERR_INVALID_ARGUMENT for a NULL argument or any other
 *         length or character.
 * @ingroup text
 */
PH_NODISCARD PH_API ph_error_t ph_hash_from_hex(const char *hex, uint64_t *out);

/* The three capability checks are named after the format, not the library behind it:
 * ph_can_use_jpeg(), ph_can_use_png(), ph_can_use_webp(). ph_get_build_info() names the
 * library. */

/**
 * @brief Whether this build has a native JPEG decoder (libjpeg-turbo), decided when the
 * library was compiled.
 * @return 1 if it does, 0 if JPEG goes through the bundled stb_image fallback.
 * @ingroup build
 */
PH_API int ph_can_use_jpeg(void);

/**
 * @brief Whether this build has a native PNG decoder, decided when the library was
 * compiled.
 *
 * Native means libpng.
 * @return 1 if PNG is decoded natively, 0 if it goes through the stb_image fallback.
 * @ingroup build
 */
PH_API int ph_can_use_png(void);

/**
 * @brief Whether this build decodes WebP with libwebp, decided when the library was
 * compiled.
 * @return 1 if it does, 0 if WebP is not supported at all (loading one returns
 * @c PH_ERR_DECODER_UNAVAILABLE; stb_image has no WebP decoder).
 * @ingroup build
 */
PH_API int ph_can_use_webp(void);

/**
 * @brief Describes how this library binary was built, as one line of text for logs and
 * bug reports.
 *
 * Space-separated `key=value` pairs, for example:
 * `version=2.0.0 jpeg=libjpeg-turbo png=libpng webp=libwebp zlib=zlib-ng threads=on simd=neon
 * mock=off`
 *
 * - `jpeg`: `libjpeg-turbo` or `stb`. A JPEG can hash a few bits apart under the two
 *   (docs/theory/comparing.md); no other build difference changes a hash;
 * - `png`: `libpng` or `stb`; `webp`: `libwebp` or
 *   `none`; `zlib`: `zlib-ng`, `zlib` or `none` (stb_image inflates PNG itself);
 * - `threads`: `on` if the batch functions can use worker threads, `off` if they always
 *   run sequentially;
 * - `simd`: the widest instruction set the library was compiled for -- `avx2`, `sse4.2`,
 *   `neon` or `none`;
 * - `mock`: `on` only in a test build that registers the mock decoder
 *   (`PHASH_ENABLE_MOCK_BACKEND`); a shipped library says `off`.
 *
 * Keys keep their meaning; later versions may add keys at the end and add values to a
 * key's list. Meant to be logged, not parsed for decisions -- to branch on a decoder,
 * use ph_can_use_jpeg(), ph_can_use_png() and ph_can_use_webp().
 * @return A static NUL-terminated string. Never NULL; the caller must not free it.
 * @ingroup build
 */
PH_API const char *ph_get_build_info(void);

#ifdef __cplusplus
}
#endif

#endif // PH_LIBPHASH_H
